[package]
name = "tored"
version = "0.1.4"
edition = "2021"

[dependencies]
arti-client = { version = "0.29", features = ["onion-service-client", "static-sqlite"] }
cookie = "0.18"
env_logger = "0.11"
http = "1.3"
log = "0.4"
tokio = { version = "1.44", default-features = false, features = ["rt-multi-thread", "macros", "signal", "net", "io-util"] }
tor-rtcompat = "0.29"
